# Conhecendo o Numpy

#### Numpy é a breviação de Numerical Python. Ele é um pacote poderoso e uito importante, utilizado para processamento numérico em Python.

#### Alguns dos destaques desse poderoso pacote são:

#### **> Objeto array multidimensional muito poderoso e performático**
#### **> Funções matemáticas para operações com arrays sem a necessidade de utilizar o laço** *for* 
#### **> Recursos de algebra linear para gerar números aleatórios**
#### **> Também pode ser aplicado com computação quântica, aplicação de modelos estatísticos, processamento de imagens e muitas outras funcionalidades**

# **Documentação:** https://numpy.org/

# Importando o Numpy

#### Para importar o pacote numpy, ou qualquer pacote que já esteja disponível em seu notebook, basta utiliar o *import* e em seguida o nome do pacote.

In [1]:
# Por questões de boas práticas, a comunidade faz o uso de alguns apelidos para alguns pacotes. 
# No caso do numpy utilizamos o "np"
# para associar o apelido ao pacote, pasta utilizar o "as" para realizar a associação

import numpy as np

# Criando uma array Numpy

In [2]:
# Para criar um array a partir de valores de sua preferência, basta utilizar o "np.array".
# Vamos utilizar a sequência de números a seguir no exemplo: 1000, 2365, 2300, 5500

np.array([1000, 2365, 2300, 5500])

# Você pode assiciar o array a uma variável. Vamos pensar esses valores são quilometragens.

km = np.array([1000, 2365, 2300, 5500])

# Agora, ao chamar a variável km, podemos acessar o nosso array

km

array([1000, 2365, 2300, 5500])

# Método *arange*

#### > O método arange serve para criar um array numpy. Com esse método, basta passar um valor por parâmetro ele criará um array com uma sequêcnia de valores correspondes ao número que foi fornecido.

#### Veja abaixo um exemplo de aplicação.

#### Para mais detalhes, acesse: https://numpy.org/doc/stable/reference/generated/numpy.arange.html

In [3]:
# Aqui podemos ver que ele criou um array com 10 elementos de 0 até 9.

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Utilizando o *loadtxt* para utilizar um dado externo

#### Para mais detalhes, acesse: https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html

In [12]:
# Para importar um arquivo para o google colaboratory, vamos utilizar o método 'files'
# Este método está presente no pacote do google.colab

#from google.colab import files
#files.upload()

# Para ler o arquivo que, basta utilizar o loadtxt
# OBS: Utilizei uma base de quilometragem no exemplo abaixo

#km = np.loadtxt(fname='carros-km.txt', dtype= int)
#km


In [16]:
# Para realizar um import de forma local, podemos utilizar diretamente o loadtxt. É nexessário apenas que os arquivos estejam dentro da pasta do projeto.

# fname > Parâmetro que indica qual arquivo eu quero carregar.
# dtype > informa o tipo da variável que queremos. 
# É importante definir o tipo. Por padrão, o numpay define o valor como float

km = np.loadtxt(fname='carros-km.txt', dtype= int)
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

#### Para mais informações sobre arrays do numpy, acesse a documentação no link abaixo: https://numpy.org/devdocs/user/basics.creation.html

# Descobrindo o tipo de dado.

#### utilizando o *type* podemos descobrir com qual tipo de dados estamos trabalhando

In [4]:
type(km)

numpy.ndarray

In [6]:
v = 5
type(v)

int

In [7]:
v1 = 2.5
type(v1)

float

In [8]:
v3 = True
type(v3)

bool

In [9]:
v4 = 'olá'
type(v4)

str

In [10]:
# Para visualizar qual o tipo de dado armazenado dentro de um array numpy, utilizamos o 'dtype'

km.dtype

dtype('int32')

#### Para mais informações sobre Tipos de dados, acesse a documentação no link: https://numpy.org/devdocs/user/basics.types.html